name: 'Terraform'

on:
  push:
    branches:
    - devint
    path:
    - 'folder_1/**'
  pull_request:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform Init
      run: terraform init
      working-directory: ./folder_1

    - name: Terraform Format
      run: terraform fmt -check
      working-directory: ./folder_1      

    - name: Terraform Plan
      run: terraform plan
      working-directory: ./folder_1

    - name: Terraform Apply
      if: github.ref == 'refs/heads/devint' && github.event_name == 'push'
      run: terraform apply -auto-approve