name: 'Terraform'

on:
  push:
    branches:
    - devint
    path:
    - 'folder_1/**'
  pull_request:

defaults:
  run:
    working-directory: folder_1

env:
  GOOGLE_PROJECT: ox-lab-robert-cam
  GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_TOKEN }}
  PRIVATE_KEY_ID: f16a48493732791209e80ceed674bad3c5376fc4

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform Init
      run: terraform init
      
    - name: Terraform Format
      run: terraform fmt -check     

    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      if: github.ref == 'refs/heads/devint' && github.event_name == 'push'
      run: terraform apply -auto-approve